#!/bin/bash

IFACE=$1
ACTION=$2

if [ "$ACTION" = "up" ]; then
    DEFAULT_GW_IFACE=$(ip ro|grep ^default|awk '{print $5}')
    if [ "$IFACE" = "$DEFAULT_GW_IFACE" ]; then
        # Remove previous rules
        RULES=$(iptables -t nat -S POSTROUTING|nl -v0|grep MASQUERADE|awk '{print $1}')
        for RULE in $RULES; do
            iptables -t nat -D POSTROUTING $RULE
        done

       # Add rule
        iptables -t nat -A POSTROUTING -o $IFACE -j MASQUERADE
    fi
fi
